title: SMapper API
summary: API for the SMapper handheld device
version: 0.1.0
description: |
    # SMapper API

    **SMapper API** is the main interface for interacting with the handheld device. It provides endpoints to:

    * List and inspect installed sensors
    * Monitor ROS topics in real time
    * Start, stop, and restart device services (including ROS nodes and launch files)
    * Record and manage ROS bag files
    * Check system status and metadata
    * Trigger system-level actions like rebooting or powering off the onboard computer (WIP)

    For the device documentation and detailed usage, visit the /docs endpoint

docs_url: /api/docs
openapi_url: /api/openapi.json
debug: true

allowed_origins:
    - "http://localhost"
    - "http://localhost:5173"
