title: SMapper API
summary: API for the SMapper handheld device
version: 0.1.0
description: |
    # SMapper API

    SMapper API is the main contact point with the handheld device. It can be used 
    to check which sensors are currently installed, start/stop/restart a set of services,
    and more, like powering off the onboard computer. For more information, you can visit
    the /docs endpoint for the device documentation

docs_url: /api/docs
openapi_url: /api/openapi.json
debug: true

allowed_origins:
    - "http://localhost"
    - "http://localhost:5173"
