device_name: SMapper
revision: "2.1"
autostart_services: false
bags_storage_path: "/home/pedros/rosbox_shared/BagStorage/"

onboard_pc:
    model: Jetson AGX Orin Development Kit

sensors:
    - name: lidar
      model: Ouster OS0-64
      type: LIDAR
      service_id: lidar_service

    - name: argus_cameras
      model: e-CAM200_CUOAGX
      type: CAMERA
      service_id: argus_cam_service

    - name: realsense
      model: Realsense D435i
      type: CAMERA
      service_id: realsense_service

services:
    - name: OusterROS
      id: lidar_service
      exec_type: "LAUNCH"
      ros_distro: humble
      ws: "$HOME/smapper/software/ros_ws"
      pkg_name: "smapper_bringup"
      exec: "lidar.launch.py"
      env:
          RMW_IMPLEMENTATION: rmw_cyclonedds_cpp

    - name: Argus Cameras
      id: argus_cam_service
      exec_type: "LAUNCH"
      ros_distro: humble
      ws: "$HOME/smapper/software/ros_ws"
      pkg_name: "smapper_bringup"
      exec: "argus_cameras.launch.py"
      env:
          RMW_IMPLEMENTATION: rmw_cyclonedds_cpp

    - name: Device Documentation
      id: dev_docs
      cwd: "/home/pedros/rosbox_shared/smapper/"
      cmd: "docker run --rm -it -p 8080:8000 -v ${PWD}:/docs squidfunk/mkdocs-material"

    # - name: Realsense Camera
    #   id: realsense_service
    #   exec_type: "LAUNCH"
    #   ros_distro: humble
    #   ws: "$HOME/smapper/software/ros_ws"
    #   pkg_name: "smapper_bringup"
    #   exec: "realsense.launch.py"
    #   env:
    #      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
