api:
    title: SMapper API
    summary: API for the SMapper handheld device
    version: 1.0.1
    description: |
        # SMapper API

        **SMapper API** is the main interface for interacting with the handheld device. It provides endpoints to:

        * List and inspect installed sensors
        * Monitor ROS topics in real time
        * Start, stop, and restart device services (including ROS nodes and launch files)
        * Record and manage ROS bag files
        * Check system status and metadata
        * Trigger system-level actions like rebooting or powering off the onboard computer (WIP)

        For the device documentation and detailed usage, visit the /docs endpoint

    docs_url: /api/docs
    openapi_url: /api/openapi.json
    debug: false

    # Use this to enable CORS for the API, for the given origins
    allowed_origins:
        - "http://10.42.0.1"
        - "http://localhost"
        - "http://localhost:5173"
        - "http://localhost:4173"

managers:
    # Add the services to be available in the API. Can be Basic Sevices or RosServices
    services:
        - name: Ouster LiDAR
          id: lidar_srv
          auto_start: false
          restart_on_failure: false
          exec_type: "LAUNCH"
          ws: "$HOME/smapper/software/ros_ws"
          pkg_name: "smapper_bringup"
          exec: "lidar.launch.py"
          env:
              RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
              CYCLONEDDS_URI: file:///home/smapper/cyclonedds.xml

        - name: Argus Cameras (4x)
          id: cameras_srv
          auto_start: false
          restart_on_failure: false
          exec_type: "LAUNCH"
          ws: "$HOME/smapper/software/ros_ws"
          pkg_name: "smapper_bringup"
          exec: "argus_cameras.launch.py"
          env:
              RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
              CYCLONEDDS_URI: file:///home/smapper/cyclonedds.xml

        - name: Odometry
          id: odometry_srv
          auto_start: false
          restart_on_failure: false
          exec_type: "LAUNCH"
          ws: "$HOME/smapper/software/ros_ws"
          pkg_name: "mola_lidar_odometry"
          exec: "ros2-lidar-odometry.launch.py lidar_topic_name:=ouster/points imu_topic_name:=/ouster/imu use_state_estimator:=True publish_localization_following_rep105:=False enforce_planar_motion:=True use_mola_gui:=False use_rviz:=False mola_lo_reference_frame:=odom mola_state_estimator_reference_frame:=odom"
          env:
              RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
              CYCLONEDDS_URI: file:///home/smapper/cyclonedds.xml

    ros:
        topic_monitor:
            topics_to_monitor:
                - /ouster/points
                - /ouster/imu
                - /camera/front_left/image_raw
                - /camera/front_right/image_raw
                - /camera/side_left/image_raw
                - /camera/side_right/image_raw
            topics_blacklist:
                - /rosout
                - /parameter_events
            monitor_rate: 2 # Seconds
            discover_rate: 3 # Seconds
            idle_timeout: 5 # Seconds

        bag_recorder:
            storage_dir: "/bags"
            env:
                RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
                CYCLONEDDS_URI: file:///home/smapper/cyclonedds.xml
            ws: "$HOME/smapper/software/ros_ws"

# Metadata about the device
device:
    name: SMapper
    revision: "2.1"

    onboard_pc:
        model: Jetson AGX Orin Development Kit

    sensors:
        - name: lidar
          model: Ouster OS0-64
          type: LIDAR
          service_id: lidar_srv

        - name: argus_cameras
          model: e-CAM200_CUOAGX
          type: CAMERA
          service_id: cameras_srv
